### ISSUE TITLE
Make sytest's application service tests pass

### ISSUE THREAD

**Issue by matrixbot** [element-hq/dendrite#531]
*This issue was originally created by [**@anoadragon453**](https://github.com/anoadragon453) at <https://github.com/matrix-org/dendrite/issues/531>.*

- [x] 01as-create - #528 #532 #533 #534 - barring v1 registration (supporting?) and #427
- [ ] 02ghost - Depends heavily on #427
- [ ] 03passive
- [ ] 04asuser
- [ ] 05lookup3pe - blocked on spec PR for https://github.com/matrix-org/matrix-doc/issues/1203 (wip)
- [ ] 06publicroomlist
- [ ] 07deactivate
